version: '2'
services:
 bbdd1_docker:
  image: mysql:5.5
  container_name: bbdd_docker
  networks:
   ccw_net:
    ipv4_address: 172.20.0.4
  environment:
   - MYSQL_ROOT_PASSWORD=pass
   - MYSQL_DATABASE=BBDD
   - MYSQL_USER=user
   - MYSQL_PASSWORD=pass
  command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8

 ccw1:
  build: .
  image: contactocero/contacto-cero-web
  container_name: contactoceroapp1
  networks:
   ccw_net:
    ipv4_address: 172.20.0.2
  depends_on:
   - bbdd1_docker
  #expose:
   # - "8080" # expose the port to other containers, but it's not exposed to the host
  environment:
   - SPRING_DATASOURCE_URL=jdbc:mysql://172.20.0.4:3306/BBDD?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   - SPRING.DATASOURCE.USERNAME=user
   - SPRING.DATASOURCE.PASSWORD=pass
   
 ccw2:
  build: .
  image: contactocero/contacto-cero-web
  container_name: contactoceroapp2
  networks:
   ccw_net:
    ipv4_address: 172.20.0.3
  depends_on:
   - bbdd1_docker
   - ccw1
  #expose:
   # - "8080" # expose the port to other containers, but it's not exposed to the host
  environment:
   - SPRING_DATASOURCE_URL=jdbc:mysql://172.20.0.4:3306/BBDD?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
   - SPRING.DATASOURCE.USERNAME=user
   - SPRING.DATASOURCE.PASSWORD=pass

 si1:
  build: ./serverinter
  image: dad_serviciointerno
  container_name: si1
  networks:
   ccw_net:
    ipv4_address: 172.20.0.5
 si2:
  build: ./serverinter
  image: dad_serviciointerno
  container_name: si2
  networks:
   ccw_net:
    ipv4_address: 172.20.0.6


 proxyapp:
  build: ./ProxyApp
  image: proxyapp_balanceador
  container_name: proxweb
  networks:
   - ccw_net
  depends_on:
   - ccw1
   - ccw2
  ports:
   - "9090:80" # Only service that is exposed to the host is the lb
   - "8443:8443"
   

 proxysi:
  build: ./ProxySI
  image: siproxy_balanceador
  container_name: proxsi
  networks:
   ccw_net:
    ipv4_address: 172.20.0.7
  depends_on:
   - si1
  expose:
   - "7000"
   
   
networks:
 ccw_net:
  driver: bridge
  ipam:
   config:
    - subnet: 172.20.0.0/16
      gateway: 172.20.0.1
